# Generated by Django 5.2.9 on 2025-12-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('1', '지원동기'), ('2', '입사 후 포부'), ('3', '성장 과정'), ('4', '성격의 장단점'), ('5', '직무 역량'), ('6', '문제 해결 경험'), ('7', '협업 경험'), ('8', '실패 경험'), ('9', '기타')], max_length=1)),
                ('content', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
    ]
