# Generated by Django 5.2.9 on 2025-12-24 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_coverletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coverletter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
