# Generated by Django 5.2.9 on 2025-12-25 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingList',
            fields=[
                ('emp_seqno', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_wanted_title', models.CharField(max_length=200)),
                ('emp_busi_nm', models.CharField(max_length=100)),
                ('co_clcd_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_wanted_stdt', models.DateField()),
                ('emp_wanted_endt', models.DateField()),
                ('emp_wanted_type_nm', models.CharField(max_length=200)),
                ('reg_log_img_nm', models.TextField()),
                ('emp_wanted_homepg_detail', models.TextField()),
                ('emp_wanted_mobile_url', models.TextField(blank=True, null=True)),
                ('emp_wanted_homepg', models.TextField(blank=True, null=True)),
                ('empn_recr_summary_cont', models.TextField(blank=True, null=True)),
                ('recr_comm_cont', models.TextField(blank=True, null=True)),
                ('emp_submit_doc_cont', models.TextField(blank=True, null=True)),
                ('emp_rcpt_mthd_cont', models.TextField(blank=True, null=True)),
                ('emp_acpt_psn_annc_cont', models.DateField(blank=True, null=True)),
                ('inqry_cont', models.TextField(blank=True, null=True)),
                ('empn_etc_cont', models.TextField(blank=True, null=True)),
                ('recruitment_process', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_recr_nm', models.CharField(max_length=100)),
                ('job_cont', models.TextField()),
                ('emp_wanted_career_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_wanted_edu_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('spt_cert_etc', models.TextField(blank=True, null=True)),
                ('recr_psncnt', models.IntegerField(blank=True, null=True)),
                ('emp_recr_memo_cont', models.TextField(blank=True, null=True)),
                ('work_region_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_seqno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_postings.jobpostinglist')),
            ],
        ),
        migrations.CreateModel(
            name='OccupationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_cd', models.CharField(max_length=100)),
                ('jobs_cd_kor_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_seqno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_postings.jobpostinglist')),
            ],
        ),
    ]
