# Generated by Django 5.2.9 on 2025-12-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_postings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "job_cd",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("job_clcd", models.CharField(max_length=100)),
                ("job_clcd_nm", models.CharField(max_length=100)),
                ("job_nm", models.CharField(max_length=100)),
                (
                    "job_lrcl_nm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "job_mdcl_nm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "job_smcl_nm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("job_sum", models.TextField(blank=True, null=True)),
                ("way", models.TextField(blank=True, null=True)),
                ("sal", models.TextField(blank=True, null=True)),
                (
                    "job_satis",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("job_status", models.CharField(blank=True, max_length=100, null=True)),
                ("exec_job", models.TextField(blank=True, null=True)),
                ("techn_know", models.TextField(blank=True, null=True)),
                ("keco_cd", models.CharField(blank=True, max_length=100, null=True)),
                ("keco_nm", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EducationBackground",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edubg_mgradu_undr", models.IntegerField()),
                ("edubg_hgradu", models.IntegerField()),
                ("edubg_cgradu_undr", models.IntegerField()),
                ("edubg_ugradu", models.IntegerField()),
                ("edubg_ggradu", models.IntegerField()),
                ("edubg_dgradu", models.IntegerField()),
                (
                    "job_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_postings.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobAbilityComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "within_job_abl_status_cmpr",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "acoss_job_abl_status",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "within_job_abl_lvl_status_cmpr",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "accoss_job_abl_lvl_status",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("job_abl_nm", models.TextField()),
                ("job_abl_cont", models.TextField()),
                (
                    "job_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_postings.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobActivityComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "within_job_actv_imprtnc_status_cmpr",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "within_job_actv_lvl_status_cmpr",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "across_job_actv_imprtnc_status",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("job_actv_imprtnc_nm", models.TextField()),
                ("job_actv_imprtnc_cont", models.TextField()),
                (
                    "job_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_postings.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobCharacterComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "within_job_chr_status_cmpr",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "across_ob_chr_status",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("job_chr_nm", models.TextField()),
                ("job_chr_cont", models.TextField()),
                (
                    "job_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_postings.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobEnvironmentComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "within_job_env_status_cmpr",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "across_job_env_status",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("job_env_nm", models.TextField()),
                ("job_env_cont", models.TextField()),
                (
                    "job_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_postings.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobInterestComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "within_intrst_status_cmpr",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "across_intrst_status",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("intrst_nm", models.TextField()),
                ("intrst_cont", models.TextField()),
                (
                    "job_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_postings.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobProspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_prospect_nm", models.CharField(max_length=100)),
                (
                    "job_prospect_ratio",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("job_prospect_inq_yr", models.IntegerField()),
                (
                    "job_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_postings.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobValuesComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "within_vals_status_cmpr",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "across_vals_status",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("vals_nm", models.TextField()),
                ("vals_cont", models.TextField()),
                (
                    "job_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_postings.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "within_knwldg_status_cmpr",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "across_knwldg_status",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "within_knwldg_lvl_status_cmpr",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "across_knwldg_lvl_status",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("knwldg_nm", models.TextField()),
                ("knwldg_cont", models.TextField()),
                (
                    "job_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_postings.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelatedCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cert_nm", models.TextField(blank=True, null=True)),
                (
                    "job_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_postings.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelatedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rel_job_cd", models.CharField(max_length=100)),
                (
                    "job_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_postings.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelatedMajor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major_cd", models.IntegerField()),
                ("major_nm", models.CharField(max_length=100)),
                (
                    "job_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_postings.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cult_lang_dpt", models.IntegerField()),
                ("soc_dpt", models.IntegerField()),
                ("edu_dpt", models.IntegerField()),
                ("engnr_dpt", models.IntegerField()),
                ("natrl_dpt", models.IntegerField()),
                ("medi_dpt", models.IntegerField()),
                ("artphy_dpt", models.IntegerField()),
                (
                    "job_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_postings.job",
                    ),
                ),
            ],
        ),
    ]
