# Generated by Django 5.2.9 on 2025-12-21 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_code', models.CharField(max_length=8, unique=True)),
                ('corp_name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsns_year', models.IntegerField()),
                ('account_id', models.CharField(max_length=50)),
                ('account_nm', models.CharField(max_length=50)),
                ('account_detail', models.CharField(max_length=50)),
                ('reprt_code', models.CharField(max_length=5)),
                ('sj_div', models.CharField(max_length=5)),
                ('thstrm_nm', models.CharField(max_length=10, null=True)),
                ('thstrm_amount', models.DecimalField(decimal_places=5, max_digits=25, null=True)),
                ('currency', models.CharField(max_length=5)),
                ('corp_code', models.ForeignKey(db_column='corp_code', on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='financial_statement.corpcode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('corp_code', 'bsns_year', 'account_id', 'account_detail'), name='corp_bsns_account')],
            },
        ),
    ]
