# Generated by Django 5.2.9 on 2025-12-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpCode',
            fields=[
                ('corp_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('corp_name', models.CharField(max_length=50)),
            ],
        ),
    ]
