# Generated by Django 5.2.9 on 2025-12-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialratio',
            name='sj_div',
        ),
    ]
