# Generated by Django 5.2.9 on 2025-12-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpcode',
            name='corp_eng_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
